### ISSUE TITLE
Guard Recursion

### ISSUE THREAD

**Issue by ParkHanbum** [ParkHanbum/uftrace#7]
```
Dump of assembler code for function wi::shifted_mask(long*, unsigned int, unsigned int, bool, unsigned int):
   0x0000000000c65c10 <+0>:     callq  *0x10caf5a(%rip)        # 0x1d30b70
   0x0000000000c65c16 <+6>:     nop
```

```
0000000000c65c10 <_ZN2wi12shifted_maskEPljjbj>:
  c65c10:       44 39 c6                cmp    %r8d,%esi
  c65c13:       44 0f b6 c9             movzbl %cl,%r9d
  c65c17:       0f 83 b3 00 00 00       jae    c65cd0 <_ZN2wi12shifted_maskEPljjbj+0xc0>
```

```
mcount-dynamic: dynamic_entry 7fffa19aed98, c65c16, 7fffa19aed10
mcount-dynamic: ============  DISASM ================
mcount-dynamic: 0xc65c10[06]:call qword ptr [rip + 0x10caf5a]
mcount-dynamic: =====================================
mcount: [mod: 7f2c4196e168, idx: 83] enter 595ec0: free
mcount: <8> enter 595ec0
mcount:  tr->flags: 0, filter mode, count: [0] 0/0
mcount: [83] exit  7f2c40cbe4f0: free
mcount: <9> exit  595ec0
mcount: task 14331 recorded 48 bytes (record count = 3)
mcount: rstack[7] ENTRY c65d76
mcount: rstack[8] ENTRY 595ec0
mcount: rstack[8] EXIT  595ec0
mcount: [mod: 7f2c4196e168, idx: 83] enter 595ec0: free
mcount: <8> enter 595ec0
mcount:  tr->flags: 0, filter mode, count: [0] 0/0
mcount: [83] exit  7f2c40cbe4f0: free
mcount: <9> exit  595ec0
mcount: task 14331 recorded 32 bytes (record count = 2)
mcount: rstack[8] ENTRY 595ec0
mcount: rstack[8] EXIT  595ec0
mcount: <8> enter c65c16
mcount:  tr->flags: 0, filter mode, count: [0] 0/0
mcount-dynamic: Let's find original code :  0
mcount-dynamic: c65c10 matched -  c65c10
mcount-dynamic: Address : c65c10 224d7c60
mcount: <9> exit  c65c16
mcount: task 14331 recorded 32 bytes (record count = 2)
mcount: rstack[8] ENTRY c65c16
mcount: rstack[8] EXIT  c65c16
mcount-dynamic: dynamic_entry 7fffa19ae7a8, 10f3de6, 7fffa19ae720
mcount-dynamic: ============  DISASM ================
mcount-dynamic: 0x10f3de0[06]:call qword ptr [rip + 0xc3cd8a]
mcount-dynamic: =====================================
mcount: Guard recursion!
```

```
(gdb) bt
#0  0x00007f38c3d25a3e in mcount_entry (parent_loc=0x7ffd455741a8, child=17776102, regs=0x7ffd45574120)
    at /home/m/git/_uftrace/libmcount/mcount.c:836
#1  0x00007f38c3d298d0 in dynamic_entry (parent_loc=0x7ffd455741a8, child=17776102, regs=0x7ffd45574120)
    at /home/m/git/_uftrace/libmcount/mcount-dynamic.c:466
#2  0x00007f38c3d4291f in __dentry__ () at /home/m/git/_uftrace/arch/x86_64/dynamic_hook.S:86
#3  0x0000000000000081 in ?? ()
#4  0x0000000001337226 in ?? ()
#5  0x00007f38c35d58ae in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ffd455747a0 in ?? ()
#7  0x000000000000000b in ?? ()
#8  0x000000000000000b in ?? ()
#9  0x00007f38c380d920 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000000000000002 in ?? ()
#11 0x0000000000000000 in ?? ()
(gdb) print* (struct mcount_thread_data *) 0x7f38c415b728
$6 = {tid = 15356, idx = 8, record_idx = 8, recursion_marker = true, in_exception = false, cygprof_dummy = 0, rstack = 0x1,
  argbuf = 0x7f38c4059010, filter = {in_count = 0, out_count = 0, depth = 1016, saved_depth = 1016, time = 0, saved_time = 0},
  enable_cached = true, shmem = {seqnum = 747, losts = 0, curr = 0, nr_buf = 2, max_buf = 2, done = false, buffer = 0x2207d00}, event = {{
      time = 0, id = 0, dsize = 0, idx = 0, data = '\000' <repeats 1007 times>}, {time = 0, id = 0, dsize = 0, idx = 0,
      data = '\000' <repeats 1007 times>}, {time = 0, id = 0, dsize = 0, idx = 0, data = '\000' <repeats 1007 times>}, {time = 0, id = 0,
      dsize = 0, idx = 0, data = '\000' <repeats 1007 times>}}, nr_events = 0, arch = {xmm = {0, 0, 0, 0, 0, 0, 0, 0}}}
```

**Comment by ParkHanbum** [comment]
```
Dump of assembler code for function wi::min_value(unsigned int, signop):
   0x0000000000c65d70 <+0>:     callq  *0x10cadfa(%rip)        # 0x1d30b70
   0x0000000000c65d76 <+6>:     nop
   0x0000000000c65d77 <+7>:     mov    %esi,%r8d
   0x0000000000c65d7a <+10>:    mov    %esi,0x1c(%rbx)
   0x0000000000c65d7d <+13>:    je     0xc65dc0 <wi::min_value(unsigned int, signop)+80>
   0x0000000000c65d7f <+15>:    lea    -0x1(%rsi),%esi
   0x0000000000c65d82 <+18>:    xor    %ecx,%ecx
   0x0000000000c65d84 <+20>:    mov    $0x1,%edx
   0x0000000000c65d89 <+25>:    callq  0xc65c10 <wi::shifted_mask(long*, unsigned int, unsigned int, bool, unsigned int)>
  # mtdp has been manipulated here. 
   0x0000000000c65d8e <+30>:    mov    0x1c(%rdi),%edx
   0x0000000000c65d91 <+33>:    mov    %eax,%ecx
  # rstack has been 1 under here.
   0x0000000000c65d93 <+35>:    mov    %eax,0x18(%rdi)

```
